name: snapshot
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: "18"
          distribution: "temurin"
          cache: maven

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure GPG Key
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Maven Verify Deploy
        run: |
          if [ ${{ github.event.pull_request.head.repo.full_name }} = ${{ github.repository }} ]; then
            mvn --no-transfer-progress --batch-mode --settings release/m2-settings.xml verify deploy
          else
            mvn --no-transfer-progress --batch-mode --settings release/m2-settings.xml verify deploy -Dgpg.skip
          fi
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
